apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ii968sz08-go
  janus-idp.io/tekton: ii968sz08-go
  backstage.io/kubernetes-id: ii968sz08-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ii968sz08-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
