apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ii968sz08-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ii968sz08-go 
  name: ii968sz08-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ii968sz08-go 
